apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-ingress
  labels:
  annotations:
    kubernetes.io/ingress.class: 'kong'
spec:
  rules:
    - host: {{ .Values.log.host }}
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: log-svc
                port:
                  number: 80
