apiVersion: v1
kind: Service
metadata:
  name: log-svc
  labels:
    app: krateo.io
    component: log
spec:
  selector:
    component: log
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080